spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sw
    password: sw
  h2:
    console:
      enabled: true

stability:
  api:
    base-url: https://api.stability.ai
