name: Workflow Dispatch Deploy # 수동 CD 파이프라인

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '배포할 태그를 입력하세요 (ex: v1.0.0)'
        required: true
        default: v1.0.0
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      # Dockerfile app 이미지 build & push
      - name: Docker Log in
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest .

      - name: push Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: ssh to ec2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              docker rmi -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest
              docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest
              cd /home/ubuntu/vata/docker/app
              docker compose up -d
              docker image prune -f
